<meta charset="utf-8" />
<script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
<script>
  function getNumber() {
    var p = new Promise(function(resolve, reject) {
      var num = Math.random();
      if (num > 0.5)
        resolve(num);
      else
        reject(num);
    });

    return p;
  }

  // case 1: 作用和 then 中传入两个参数类似
  getNumber()
    .then(function(data) {
      console.log('resolve');
      console.log(data);
    })
    .catch(function(data) {
      console.log('reject');
      console.log(data);
    });



  // case 2: then 的第一个参数的回调中，如果出现错误，会进入 catch
  // 当然前提是你得先进入 resolve 的回调中 ...
  getNumber()
    .then(function(data) {
      console.log('resolve');
      console.log(data);

      // error
      console.log(a);
    })
    .catch(function(data) {
      console.log(data);  // ReferenceError: a is not defined(…)
    });
</script>